name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: php artisan test
